---
services:
  pve-nuxbox-3-cloudflared:
    image: cloudflare/cloudflared
    container_name: pve-nuxbox-3-cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=__CF_PVE_NUXBOX_3_TUNNEL_TOKEN__
    restart: always
    networks:
      - myservice-proxy
  pve-prodesk-cloudflared:
    image: cloudflare/cloudflared
    container_name: pve-prodesk-cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=__CF_PVE_PRODESK_TUNNEL_TOKEN__
    restart: always
    networks:
      - myservice-proxy

networks:
  myservice-proxy:
